DIALOGUE = [
	["ANTAG", "PROTAG, you'll never beat me.", "I've ensured of that."],
    ["PROTAG", "I will fell you, great beast, and save the world!", " "],
	["ANTAG", "Ha, with what?", "None of the puny items in that dungeon can fell me."],
	["PROTAG", "You've forgotten aboout just one, ANTAG.", " "],
	["PROTAG", "My trusty BOCARINA.", " "],
	["ANTAG", "What's a BOCARINA?", " "],
	["PROTAG", "A BOCARINA is a professional grade nose flute.", "A BOCARINA is to a nose flute as a Steinway is to a piano."],
	["ANTAG", "Ha, so it's a musical instrument?", "I can't die from that."],
	["PROTAG", "You're wrong!", "It's a 'musical instrument'!"],
    ["ANTAG", "GO AHEAD.", "TRY AND BEAT ME!"],
    ["PROTAG", "FINE.", "INITIATE BOCARINA!"],
    ["ANTAG", "INITIATE ANTAG POWERS!", " "],
    ["PROTAG", "*plays BOCARINA*", " "],
    ["ANTAG", "NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!", " "],
    ["ANTAG", "*dies*", " "],
    ["PROTAG", "YES!!", " "],
    ["PROTAG", "...What happens now that I've beaten the game...?", " "],
    [" ", "....", "........"],
    [" ", "............", "................"],
    ["PYQUEST: THIRD ACT", "A Game of Bath Scenes Final Chapter: HD Re;Master XI-2", "No [Visual] Novel No Life (Or, No Novel No Game)"],
    ["COMPUTERIZED VOICE", "Access granted. Authorizing reanimation sequence.", "Beginning in three... two... one."],
	["VILLAGER", "..", "..."],
	["VILLAGER", "........", "....el.....up........"],
	["VILLAGER", "...Hello?", "Wake up!"],
	["PROTAG", "Where am I? I just finished the first dungeon in that awesome", "game. Was that a dream... or reality?"],
	["VILLAGER", "You must save our people, PROTAG! You're our only hope!", " "],
	["PROTAG", "...Oh. The game's still going. UGH. Why can't this be a", "first person shooter instead of this weaboo garbage visual novel...?"],
	["PROTAG", "That probably means that this game will have a DLC bath scene, huh?", "Or a sequel set entirely at the beach?"],
	["PROTAG", "I can see it: 'Pyquest Story Mode II: Swim Club.'", "Kill me now."],
	["VILLAGER", "You will be dead soon if you don't do something to save our people.", "The Empire is attacking from the East."],
	["PROTAG", "Can I have a compass?", " "],
	["VILLAGER", "...huh?", " "],
	["PROTAG", "I said 'Can I have a compass?'", " "],
	["VILLAGER", "Oh, of course you can have a compass.", "They're sold at the village store. Feel free to purchase one~!"],
	["VILLAGER", "You see, our village makes 98% of its GDP from ", "the sale of artisenal compasses... "],
	["VILLAGER", "If we gave them away to every schmo off the street,", "we'd be riddled with poverty!"],
	["PROTAG", "I don't have any money, so just tell me which way East is.", " "],
	["VILLAGER", "Oh, of course you can know which way East is. You can find that", "information out at the village store. Feel free to purchase it~!"],
	["VILLAGER", "You see, our village makes 2% of its GDP from the ", "sale of directional knowledge... "],
	["VILLAGER", "If we gave that information away to every schmo off the street,", "we'd be riddled with poverty."],
	["VILLAGER", "That information costs 25% of the amount we'd normally charge for a compass.", " "],
	["PROTAG", "I don't have any money. If you won't tell me which way this", "'Empire' is coming from, all your village's people will die."],
	["VILLAGER", "'This world is full of absurdities as a matter of course.'", " "],
	["    ", "..", " "],
	["    ", "....", " "],
	["    ", "........", " "],
	["VILLAGER", "Wh-- why are you strangling me, PROTAG!?", " "],
	["VILLAGER", "STOP! GUARDS!? ", "I'LL REALLY DIE IF THIS KEEPS UP! "],
    ["VILLAGER", "[dies]", " "],
	["    ", ">>You are now an implicit criminal guilty of murder.", " "],
	["PROTAG", "'A fool who knows what he is, is far more fearsome", "than a fool who thinks he's smart.'"],
	["PROTAG", "This game really has taken a downhill turn.", "Visual novels suck."],
	["PROTAG", "Like, I wasn't even given a choice if I wanted to kill that guy or not.", "Maybe it's only this visual novel that sucks."],
	["CHOICE TIME: A. I, S. 9", "Will you take VILLAGER's life?", "Press 'y' to make his head spin. Press 'n' to let friendship blossom."],
	["PROTAG", "YOU CAN'T HAVE EX POST FACTO CHOICES.", "THAT'S NOT HOW DECISIONS WORK."],
	["PROTAG", "THAT'S NOT HOW BRANCHING PATHS WORK.", "This is worse than a Telltale game. Fine. Whatever"],
	["PROTAG", "I'm not being the main character of this visual novel anymore.", "This 'story' sucks anyways."],
	["    ", "....", " "],
    ["    ", "It requires Congressional or State approval to", "invoke martial law."],
	["    ", "......", " "],
    ["    ", "This visual novel would have", "been easier to make in PowerPoint."],
	["    ", ".......", " "],
	["    ", "In this game's production, Noveltry went through", "internal termoil over the visual novel section."],
	["    ", "........", " "],
	["    ", "This game went through a production cycle ", "much shorter than that of FFXV."],
	["    ", "..........", " "],
	["    ", "Sardines are full of nutrients, like omega-3 fatty acids!", " "],
	["    ", "............", " "],
	["    ", "Look forward to the full version of this game!", "Coming Spring 2018."],
	["    ", "..............", " "],
	["    ", "Telnet is not encrypted.", "SSH is encrypted."],
    ["    ", "....................", " "],
    ["    ", "............................", " ..........................................."],
	["PROTAG", "Will this never end?", "Am I doomed to walk this village eternally...?"],
	["PROTAG", "I've been standing in this spot for twenty-two years, yet I haven't aged.", "The Empire never came."],
	["PROTAG", "My only friend is this tree standing next to me.", " "],
	["PROTAG", "Why...? Why did it have to come to this...?", " "],
	["PROTAG", "Hey, TREE, 'want to commit double suicide with me?'", " "],
	["TREE", "...", " "],
	["PROTAG", "*STRANGLES TREE*", " "],
	["TREE", "...", " "],
	["TREE", "[dies]", " "],
	["    ", "PYQUEST STORY MODE -- END", " "]


]
